apiVersion: v1 
kind: Namespace
metadata: 
  name: leo-sales
--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: leo-sales
  namespace: leo-sales
spec:
  selector:
    matchLabels:
      app: leo-sales
  template:
    metadata:
      labels:
        app: leo-sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: leo-sales
        image: sales-api-image
