apiVersion: v1 
kind: Namespace
metadata: 
  name: leo-sales
--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: leo-sales
  namespace: leo-sales
spec:
  selector:
    matchLabels:
      app: leo-sales
  template:
    metadata:
      labels:
        app: leo-sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: leo-sales
        image: sales-api-image
        ports: 
        - name: sales-api
          containerPort: 3000
        - name: sales-api-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            port: 4000
            path: /debug/readiness
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            port: 4000
            path: /debug/liveness
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1 
kind: Service 
metadata:
  name: leo-sales 
  namespace: leo-sales
spec:
  type: ClusterIP
  selector:
    app: leo-sales
  ports:
  - name: sales-api
    port: 3000
    targetPort: sales-api
  - name: sales-api-debug
    port: 4000
    targetPort: sales-api-debug



